// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83gzDfr1ahnY58EKAkGOSu2i460lc0RI',
    appId: '1:916353048377:web:721b7969cd24703f7c12e8',
    messagingSenderId: '916353048377',
    projectId: 'reddit-clone-flutter-14936',
    authDomain: 'reddit-clone-flutter-14936.firebaseapp.com',
    storageBucket: 'reddit-clone-flutter-14936.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1GxDfCpMeLovLvLxCdihtxjKf2rngHo',
    appId: '1:916353048377:android:3dc5e72f05db37267c12e8',
    messagingSenderId: '916353048377',
    projectId: 'reddit-clone-flutter-14936',
    storageBucket: 'reddit-clone-flutter-14936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcZqrhPLkCYKsPxCXKHr2HP79SHejN24c',
    appId: '1:916353048377:ios:19e3bdf14cef5cae7c12e8',
    messagingSenderId: '916353048377',
    projectId: 'reddit-clone-flutter-14936',
    storageBucket: 'reddit-clone-flutter-14936.appspot.com',
    iosClientId: '916353048377-s06t6r8593cl0p41clr0kdt4mdogbl42.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
